[package]
name = "say-hi-cli"
version = "0.1.0"
edition = "2018"
description = "say hi on the command line"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
say-hi = "0.1.2"
